#!/usr/bin/env bash

set -e

echo "🔧 Installing base packages..."

# Slack & Discord (from AUR, assuming yay is installed)
yay -S --needed --noconfirm slack-desktop discord zoom-us

# Docker & Docker Compose
sudo pacman -S --needed --noconfirm docker docker-compose
sudo systemctl enable --now docker.service
sudo usermod -aG docker "$USER"

# Node Version Manager (nvm) setup for Zsh
if [ ! -d "$HOME/.nvm" ]; then
  git clone https://github.com/nvm-sh/nvm.git ~/.nvm
  cd ~/.nvm && git checkout v0.39.7
  echo 'export NVM_DIR="$HOME/.nvm"' >> ~/.zshrc
  echo '[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"' >> ~/.zshrc
  export NVM_DIR="$HOME/.nvm"
  source "$NVM_DIR/nvm.sh"
else
  export NVM_DIR="$HOME/.nvm"
  source "$NVM_DIR/nvm.sh"
fi

# Install Node.js (LTS) + npm + pnpm
nvm install --lts
npm install -g pnpm zx

# uv (Python fast package manager)
curl -Ls https://astral.sh/uv/install.sh | bash

# GUI tools
sudo pacman -S --needed --noconfirm \
  wofi waybar mako neovim  stow \
  bitwarden-cli wf-recorder slurp grim btop tree \
  hyprpaper hyprlock hypridl zshe



# VPN support
sudo pacman -S --needed --noconfirm openvpn networkmanager-openvpn

cd dotfiles
# Stow dotfiles
if [ ! -d "$HOME/.config" ]; then
  mkdir -p "$HOME/.config"
fi

stow -t "$HOME" --adopt --restow mako nvim waybar wofi mako kitty tmux zsh hyprland

git submodule update --init --recursive

ZSH_FILE="$HOME/.config/zsh/zshrc"   

ZX_ALIAS_LINE='if command -v zx >/dev/null 2>&1; then eval "$(zx $HOME/.config/zsh/main.mjs)"; fi'

if ! grep -Fq "$ZX_ALIAS_LINE" "$ZSH_FILE" 2>/dev/null; then
  printf "\n# Load aliases generated by google/zx\n%s\n" "$ZX_ALIAS_LINE" >> "$ZSH_FILE"
  echo " [ok] Added zx-alias loader to $ZSH_FILE"
else
  echo " [skip] zx-alias loader already present in $ZSH_FILE"
fi


echo "✅ Base setup complete. You may need to log out/in to apply Docker group changes."

