# Extra autostart processes
# exec-once = uwsm-app -- my-service

# Start tmux session to load config and plugins (only if no session exists)
exec-once = tmux has-session 2>/dev/null || tmux new-session -d -s _init
exec-once = uwsm-app -- bitwarden-desktop
exec-once = omarchy-launch-webapp "https://music.youtube.com/"
exec-once = omarchy-launch-webapp "https://web.whatsapp.com/"
exec-once = omarchy-launch-or-focus-webapp discord "https://discord.com/channels/@me"
exec-once = uwsm-app -- slack
exec-once = rclone mount gdrive: ~/GDrive/ --vfs-cache-mode writes &
exec-once = hyprshell run

windowrule = match:class Bitwarden, workspace 9
windowrule = match:class .*iscord.*, workspace 13
windowrule = match:class [Ss]lack, workspace 19
windowrule = match:class .*hatsapp.*, workspace 14
windowrule = match:class .*usic\.youtube.*, workspace 15